-- VitaDev: esquema propuesto v1. Ejecutar solamente en una base de destino vacía.
-- No publica tablas a la Data API ni usa Supabase Auth.
CREATE SCHEMA vitadev;
REVOKE ALL ON SCHEMA vitadev FROM PUBLIC;
SET search_path TO vitadev, pg_catalog;
CREATE TABLE schema_migrations(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE roles(code text PRIMARY KEY CHECK(code IN ('ADMIN','EMPLOYEE')));
CREATE TABLE permissions(code text PRIMARY KEY);
CREATE TABLE permission_profiles(code text PRIMARY KEY,label text NOT NULL);
CREATE TABLE profile_permissions(profile_code text REFERENCES permission_profiles(code),permission_code text REFERENCES permissions(code),PRIMARY KEY(profile_code,permission_code));
CREATE TABLE employees(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email text NOT NULL,legajo text NOT NULL,version integer NOT NULL DEFAULT 1 CHECK(version>0),
 first_name text NOT NULL,last_name text NOT NULL,position text NOT NULL,area text NOT NULL,
 dni text,birth_date date,phone text,manager_id bigint REFERENCES employees(id) DEFERRABLE INITIALLY DEFERRED,
 hire_date date,work_modality text,labor_status text NOT NULL,availability text NOT NULL,
 photo_path text,created_at timestamptz,updated_at timestamptz,
 extra_data jsonb NOT NULL DEFAULT '{}',CHECK(manager_id IS NULL OR manager_id<>id)
);
CREATE UNIQUE INDEX employee_email_unique ON employees(lower(email));
CREATE UNIQUE INDEX employee_legajo_unique ON employees(lower(legajo));
CREATE TABLE employee_skills(employee_id bigint REFERENCES employees(id),position integer NOT NULL,skill text NOT NULL,PRIMARY KEY(employee_id,position));
-- No se inventa un modelo para capacitación/certificaciones: formato existente conservado en extra_data.
CREATE TABLE users(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,email text NOT NULL,
 password_hash text,role_code text NOT NULL REFERENCES roles(code),status text NOT NULL CHECK(status IN ('ACTIVE','DISABLED')),
 employee_id bigint UNIQUE REFERENCES employees(id),profile_code text NOT NULL REFERENCES permission_profiles(code),
 last_login_at timestamptz,created_at timestamptz,updated_at timestamptz,legacy_permissions jsonb NOT NULL DEFAULT '[]',legacy_last_access text,
 CHECK(role_code<>'EMPLOYEE' OR employee_id IS NOT NULL),
 CHECK((role_code='ADMIN')=(profile_code='ADMINISTRATOR'))
);
CREATE UNIQUE INDEX user_email_unique ON users(lower(email));
CREATE TABLE sessions(token_hash text PRIMARY KEY,user_id bigint NOT NULL REFERENCES users(id),csrf text NOT NULL,expires_at double precision NOT NULL,last_seen double precision NOT NULL,idle_seconds integer NOT NULL);
CREATE INDEX sessions_user_id_idx ON sessions(user_id);
CREATE TABLE login_attempts(key text PRIMARY KEY,count integer NOT NULL,expires_at double precision NOT NULL);
CREATE TABLE attachments(
 scope text NOT NULL CHECK(scope IN ('crm','request','leave')),id text NOT NULL,
 name text NOT NULL,mime text NOT NULL,storage_path text NOT NULL,owner_employee_id bigint REFERENCES employees(id),
 PRIMARY KEY(scope,id)
);
CREATE TABLE clients(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,
 name text NOT NULL,legal_name text,cuit text,organization_type text,country text,province text,city text,address text,postal_code text,
 owner_employee_id bigint REFERENCES employees(id),status text NOT NULL,logo_path text,since date,
 created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}'
);
CREATE UNIQUE INDEX client_cuit_unique ON clients(cuit) WHERE cuit IS NOT NULL;
CREATE TABLE contacts(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,
 client_id bigint NOT NULL REFERENCES clients(id),first_name text NOT NULL,last_name text NOT NULL,email text NOT NULL,
 position text,phone text,role text,status text NOT NULL,is_principal boolean NOT NULL DEFAULT false,
 created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}',UNIQUE(id,client_id)
);
CREATE UNIQUE INDEX contact_principal ON contacts(client_id) WHERE is_principal AND status='Activo';
CREATE TABLE products(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,
 name text NOT NULL,description text,product_type text,status text NOT NULL,
 created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}'
);
CREATE UNIQUE INDEX product_name_unique ON products(lower(name));
CREATE TABLE product_plans(product_id bigint REFERENCES products(id),name text NOT NULL,position integer NOT NULL,PRIMARY KEY(product_id,name));
CREATE TABLE product_options(product_id bigint REFERENCES products(id),name text NOT NULL,position integer NOT NULL,PRIMARY KEY(product_id,name));
CREATE TABLE subscriptions(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,
 client_id bigint NOT NULL REFERENCES clients(id),product_id bigint NOT NULL REFERENCES products(id),plan text,
 status text NOT NULL,start_date date,created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}',
 UNIQUE(id,client_id),UNIQUE(id,product_id),FOREIGN KEY(product_id,plan) REFERENCES product_plans(product_id,name)
);
CREATE TABLE subscription_options(
 subscription_id bigint NOT NULL,product_id bigint NOT NULL,option_name text NOT NULL,position integer NOT NULL,
 PRIMARY KEY(subscription_id,option_name),FOREIGN KEY(subscription_id,product_id) REFERENCES subscriptions(id,product_id),
 FOREIGN KEY(product_id,option_name) REFERENCES product_options(product_id,name)
);
CREATE TABLE contracts(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,client_id bigint NOT NULL REFERENCES clients(id),
 number text NOT NULL,status text NOT NULL,signed_date date,start_date date,end_date date,renewal text,period text,currency text,
 amount numeric(14,2),notes text,document_scope text,document_id text,
 created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}',UNIQUE(id,client_id),
 FOREIGN KEY(document_scope,document_id) REFERENCES attachments(scope,id),CHECK(end_date IS NULL OR end_date>=start_date)
);
CREATE UNIQUE INDEX contract_number_unique ON contracts(lower(number));
CREATE TABLE contract_subscriptions(
 contract_id bigint NOT NULL,subscription_id bigint NOT NULL,client_id bigint NOT NULL,position integer NOT NULL,
 PRIMARY KEY(contract_id,subscription_id),FOREIGN KEY(contract_id,client_id) REFERENCES contracts(id,client_id),
 FOREIGN KEY(subscription_id,client_id) REFERENCES subscriptions(id,client_id)
);
CREATE TABLE requests(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,
 client_id bigint NOT NULL REFERENCES clients(id),subscription_id bigint NOT NULL,contact_id bigint,
 title text NOT NULL,description text NOT NULL,status text NOT NULL,priority text NOT NULL,request_type text,queue text,
 agent_employee_id bigint REFERENCES employees(id),created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}',
 UNIQUE(id,client_id),FOREIGN KEY(subscription_id,client_id) REFERENCES subscriptions(id,client_id),
 FOREIGN KEY(contact_id,client_id) REFERENCES contacts(id,client_id)
);
CREATE INDEX request_agent_status ON requests(agent_employee_id,status);
CREATE TABLE request_attachments(request_id bigint REFERENCES requests(id),scope text NOT NULL DEFAULT 'request' CHECK(scope='request'),attachment_id text NOT NULL,position integer NOT NULL,PRIMARY KEY(request_id,attachment_id),FOREIGN KEY(scope,attachment_id) REFERENCES attachments(scope,id));
CREATE TABLE comments(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,request_id bigint NOT NULL REFERENCES requests(id),
 body text NOT NULL,actor_user_id bigint REFERENCES users(id),actor_employee_id bigint REFERENCES employees(id),
 actor_label text NOT NULL,created_at timestamptz NOT NULL,extra_data jsonb NOT NULL DEFAULT '{}'
);
CREATE TABLE comment_attachments(comment_id bigint REFERENCES comments(id),scope text NOT NULL DEFAULT 'request' CHECK(scope='request'),attachment_id text NOT NULL,position integer NOT NULL,PRIMARY KEY(comment_id,attachment_id),FOREIGN KEY(scope,attachment_id) REFERENCES attachments(scope,id));
CREATE TABLE tasks(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,request_id bigint NOT NULL,client_id bigint NOT NULL,
 owner_employee_id bigint NOT NULL REFERENCES employees(id),title text NOT NULL,status text NOT NULL,priority text NOT NULL,
 due_date date,done boolean NOT NULL DEFAULT false,created_at timestamptz,updated_at timestamptz,extra_data jsonb NOT NULL DEFAULT '{}',
 FOREIGN KEY(request_id,client_id) REFERENCES requests(id,client_id)
);
CREATE INDEX task_owner_status ON tasks(owner_employee_id,status);
CREATE TABLE leaves(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version integer NOT NULL DEFAULT 1,
 employee_id bigint NOT NULL REFERENCES employees(id),leave_type text NOT NULL,start_date date NOT NULL,end_date date NOT NULL,
 days integer NOT NULL CHECK(days>0),status text NOT NULL,reason text,attachment_scope text,attachment_id text,
 created_at timestamptz,updated_at timestamptz,created_by_label text,resolved_at timestamptz,resolved_by_label text,resolution_comment text,
 extra_data jsonb NOT NULL DEFAULT '{}',CHECK(end_date>=start_date),FOREIGN KEY(attachment_scope,attachment_id) REFERENCES attachments(scope,id)
);
CREATE INDEX leave_employee_period ON leaves(employee_id,status,start_date,end_date);
CREATE TABLE audit_entries(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,source_table text NOT NULL,source_id bigint NOT NULL,
 action text NOT NULL,actor_user_id bigint REFERENCES users(id),actor_employee_id bigint REFERENCES employees(id),actor_label text,
 entity_type text,entity_id bigint,employee_id bigint REFERENCES employees(id),client_id bigint REFERENCES clients(id),
 request_id bigint REFERENCES requests(id),leave_id bigint REFERENCES leaves(id),user_id bigint REFERENCES users(id),
 occurred_at timestamptz,reference text,comment text,changed_fields jsonb,metadata jsonb NOT NULL DEFAULT '{}',
 UNIQUE(source_table,source_id)
);
CREATE INDEX audit_time ON audit_entries(occurred_at);
-- El backend conserva la autorización. No habilitar el esquema en PostgREST.
DO $$ DECLARE t record; BEGIN
 FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='vitadev' LOOP
  EXECUTE format('ALTER TABLE vitadev.%I ENABLE ROW LEVEL SECURITY',t.tablename);
 END LOOP;
END; $$;
REVOKE ALL ON ALL TABLES IN SCHEMA vitadev FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA vitadev FROM PUBLIC;
INSERT INTO schema_migrations(version) VALUES(1);
